server:
  servlet:
    encoding:
      charset: utf-8
      force: true
    # url rewrite 문제 해결
    session:
      tracking-modes: cookie
      timeout: 30m
  port: 8080

spring:
  mustache:
    servlet:
      expose-session-attributes: true
      expose-request-attributes: true

  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${RDS_HOST}:3306/sociallize # aws
      username: ${RDS_USERNAME}
      password: ${RDS_PASSWORD}
  h2:
    console:
      enabled: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
    defer-datasource-initialization: false

  # m3u8 을 비디오 타입으로 하기위해 추가
  http:
    media-types:
      hls:
        - application/vnd.apple.mpegurl